ACCOUNT_TYPE_YASOUND = 'yasound'
ACCOUNT_TYPE_FACEBOOK = 'facebook'
ACCOUNT_TYPE_TWITTER = 'twitter'
SINGLE_ACCOUNT_TYPES = (ACCOUNT_TYPE_YASOUND, ACCOUNT_TYPE_FACEBOOK, ACCOUNT_TYPE_TWITTER)

ACCOUNT_MULT_FACEBOOK = 'FB'
ACCOUNT_MULT_TWITTER = 'TW'
ACCOUNT_MULT_YASOUND = 'YA'

ACCOUNT_TYPE_SEPARATOR = ','

ACCOUNT_TYPES_FACEBOOK = (ACCOUNT_MULT_FACEBOOK, ACCOUNT_TYPE_FACEBOOK)
ACCOUNT_TYPES_TWITTER = (ACCOUNT_MULT_TWITTER, ACCOUNT_TYPE_TWITTER)
ACCOUNT_TYPES_YASOUND = (ACCOUNT_MULT_YASOUND, ACCOUNT_TYPE_YASOUND)

SUBSCRIPTION_NONE = 'none'
SUBSCRIPTION_PREMIUM = 'premium'

GROUP_NAME_VIP = 'vip'

APP_KEY_COOKIE_NAME = 'app_key'
APP_KEY_IPHONE = 'yasound_iphone_app'

