#!/bin/sh -e
# ============================================
#  yapush - Starts the push daemon.
# ============================================

DAEMON=/usr/bin/python2.6
ARGS="/var/www/push.yasound.com/root/yapush/run.py"
PIDFILE=/tmp/yapush.pid

case "$1" in
  start)
    echo "Starting server"
    /sbin/start-stop-daemon --start --pidfile $PIDFILE \
        --user customer --group customer \
        -b --make-pidfile \
        --chuid customer \
        --exec $DAEMON $ARGS
    ;;
  stop)
    echo "Stopping server"
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE --verbose
    ;;
  restart)
    echo "Restarting server"
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE --verbose --oknodo
    /sbin/start-stop-daemon --start --pidfile $PIDFILE \
        --user customer --group customer \
        -b --make-pidfile \
        --chuid customer \
        --exec $DAEMON $ARGS
    ;;
  *)
    echo "Usage: /etc/init.d/yapush {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
