# DO NOT EDIT
# This file is generated by puppet

#Gunicorn configuration file.


#bind = '127.0.0.1:9000'
bind =  'unix:/data/tmp/gnucorn_yaapp.sock'
backlog = 2048

#
# Worker processes
#

workers = 33
worker_class = 'egg:gunicorn#sync'
worker_connections = 1000
timeout = 30
keepalive = 2

#
# Debugging
#

debug = False
spew = False

#
# Server mechanics
#

daemon = True
pidfile = '/data/tmp/gnucorn_yaapp.pid'
umask = 0
user = None
group = None
tmp_upload_dir = None

#
#   Logging
#

logfile = '-'
loglevel = 'info'
accesslog = '-'

#
# Process naming
#

proc_name = None

#
# Server hooks
#

def post_fork(server, worker):
    server.log.info("Worker spawned (pid: %s)", worker.pid)

def pre_fork(server, worker):
    pass

def pre_exec(server):
    server.log.info("Forked child, re-executing.")

def when_ready(server):
    server.log.info("Server is ready. Spwawning workers")
